language: node_js
node_js:
    - "lts/*"
notifications:
    email: false
cache: false
sudo: required
script: skip
branches:
    only:
        - master
jobs:
    include:
        - stage: lint
          script: npm run lint
        - stage: test
          script: npm run test
stages:
    - lint
    - test
